### ISSUE TITLE
[BUG] Settings not used

### ISSUE THREAD

**Issue by cd-FileX** [Akylas/OSS-DocumentScanner#124]
### Version

1.4.4.45

### What platform are you using?

Android

### OS Version

Android 10

### What happened?

First start, set auto-scan to false and flash is auto-false. Though deslite of these settings, both are somehow enabled and the app crashing as soon as I try to scan.

### Relevant log output

```shell
?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@cd-FileX ok not good. Will try to reproduce
THanks

**Comment by farfromrefug** [comment]
@cd-FileX i tried to reproduce your issue but could not on my phone.
* is that only happening on first run? Or is flash always triggering without it being enabled?
* same thing for auto Scan?
* if you switch flashmode then put it back to "noFlash" does it work?

**Comment by farfromrefug** [comment]
@cd-FileX could you please try with that build for the auto scan crash https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? With this one i would get a bug report (dont forget to restart the app after the crash for the log to be sent).

As for the flash it is really weird indeed. Have you tried that app https://github.com/GrapheneOS/Camera ? Does it work with it ? We use the same camera lib

**Comment by farfromrefug** [comment]
@cd-FileX ok it tells me the autoScan crashes "depending" on the scan it sees with the camera.
As for flash issue very weird!

**Comment by farfromrefug** [comment]
@cd-FileX the flash issue might be fixed in 1.4.6

**Comment by farfromrefug** [comment]
@cd-FileX that s strange that is actually the flashlight toggle that i fixed :s 
Could you again please try with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? (restart the app after the crash)
Really sorry for the trouble

**Comment by farfromrefug** [comment]
@cd-FileX great i got the crash and it is something i already partially fixed.
the issue comes from trying to draw an image too big. Your phone seems to have 48mp camera => ~180mb image. Quite big :D
In the build you have i already added a limit to the capture image size. THought that would be enough. Do you remember if the crash happened while capturing a new image or while "browsing" already captured (with older builds) images?

I am starting to think i wont put a cap to the capture image size but instead try to reduce image before drawing it in case it is too big. Just a bit afraid there might be other issues with such big images

**Comment by farfromrefug** [comment]
@cd-FileX i rewrote big parts of the app for better memory management. I will close this for now but please dont hesitate to open if you still face an issue
