### ISSUE TITLE
[FEATURE REQUEST] Add support to import existing pdf

### ISSUE THREAD

**Issue by Sera-Moon** [Akylas/OSS-DocumentScanner#138]
**Is your feature request related to a problem? Please describe.**
I wanted to import an existing pdf file with a scanned text into the app to edit the images afterwards (e.g. background) and to use ocr so that I can export it as a searchable document. However, I cannot import a pdf file on either the android smartphone or the ipad. 

**Describe the solution you'd like**
Support pdf as an import file format.

**Describe alternatives you've considered**

**Additional context**

**Comment by farfromrefug** [comment]
@Sera-Moon This is not supported yes. And i am not sure i will. It is tricky because there can be many things in a PDF and this app only supports "images". So it would mean either import each PDF page as an image or only importing images from the PDF.
Plus i would not be able to import pdf "text" as data to be used in this app.

I ll keep this open but wont be easy to do as it might never fill everyone's needs

**Comment by farfromrefug** [comment]
@Sera-Moon it is now implemented in latest android version (ios to come later)

**Comment by Sera-Moon** [comment]
Thx, i will close this issue.
