### ISSUE TITLE
[FEATURE REQUEST] Use Document Scanner API by ML Kit

### ISSUE THREAD

**Issue by jeffconrad18** [Akylas/OSS-DocumentScanner#168]
**Is your feature request related to a problem? Please describe.**
I would like to use ML Kit's clean feature, so adding the Document Scanner API would be useful.

**Describe the solution you'd like**
Add Document Scanner API by ML Kit

**Additional context**
[Document Scanner API by ML Kit](https://developers.google.com/ml-kit/vision/doc-scanner)

**Comment by farfromrefug** [comment]
@jeffconrad18 thanks for the feature request. For now i dont really plan on using MLKit. The reasoning is that this is app is 100% open source so that you can trust the app to handle your documents.
Moreover i tend to try to avoid any Google related product in my apps (concurrence, data privacy, big tech...)
But i want to remain open. If more users ask for this i will look at it and add it to the google play version (will never make it in the fdroid version though)
