### ISSUE TITLE
[BUG] Extreme touch sensitivity in magnifier crop tool

### ISSUE THREAD

**Issue by ghost** [Akylas/OSS-DocumentScanner#194]
### Version

v1.5.11.68 from F-Droid

### What platform are you using?

Android

### OS Version

Android 14

### What happened?

The magnifier is so extremely sensitive that using it is cumbersome and precarious. 

By contrast, Google Drive's "Scan" function couples the magnifier with a reducing the motion sensitivity of the touch, so one would need to move the finger a large distance on the screen to move the magnifier just a tiny amount on the capture. Such reduction in movement is necessary for the fine cropping that the magnifier is intended to serve.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment]
@48-mq OK  Will make that a setting

**Comment by 48-mq** [comment]
@farfromrefug Is there any advantage to keeping it the way it is? Adding a setting for this seems unnecessary, and would bloat the UX.

May I suggest you use the Google Drive app to scan a few pages on your phone? It'll give you a clear idea of what I am driving at for both this issue as well as #119 

Alternatively, please let me know if you cannot access the Google Drive app, and in that case I will record a screen capture video for you walking you through the same feature.

**Comment by farfromrefug** [comment]
@48-mq i cant install google drive app on my phone. I dont have google play services. So if you can make a video would be nice (enable the dev setting to show touch pointer).
About the idea of making it a setting, the reasoning is that you are the first user to report this. Which could mean that most users are ok or like the current setting (i am one of them).
So making it a setting would allow anyone to find the right setting for them

**Comment by 48-mq** [comment]
Sure, in the coming days I will try to record videos showing this aspect in Google Drive and also in OSS-DS. However, these videos would still only give you a vague sense of what the user experience is like, because (for instance) they would not demonstrate whether I moved my finger very slowly/diligently or very fast/recklessly on the screen to cause the extent of movements shown in the magnifier in each app. The usability issue here is that the very slightest movement of the finger causes the magnifier to skip several pixels, because it is also magnifying the touch movements.

Also, it's quite possible that devices with a lower screen size/screen resolution/camera resolution/digitizer sensitivity would not exhibit this issue, even when running the same app code.

In either case, the functionality of cropping captured photos is at the very heart of what a document scanner app does, so unless an app works at least reasonably well in this aspect right from the install, I personally would be likely to simply uninstall the app and move on, instead of trying to patiently calibrate the magnifier sensitivity setting to see if I can make it usable. Though such a setting could perhaps be useful to other users, from a fine tuning/preference setting perspective. I have also never seen such sensitivity selection setting on any of the other scanner apps (whether open source or otherwise), though I will try to demonstrate the reduced sensitivity effect in the Google Drive app.

All this being said, of course mine is only the opinion of one single user, and this is really your choice to make as the developer :)

**Comment by farfromrefug** [comment]
@48-mq i can understand your point. But be careful in saying any other scanner app does it the way you think. For example just tried genius scan and it has a sensitivity of 1 which is the current OSS Document Scanner default.

That being said i will lower the default while also allowing to change the setting.

**Comment by farfromrefug** [comment]
@48-mq there is a new version available addressing both issues

**Comment by 48-mq** [comment]
Hi @farfromrefug sorry I got busy and still haven't made any videos. Did test the new version, and the magnifier repositioning looks great, thank you!

There's a new bug which I will notify in a separate issue. However, the stickiness of the touch has remained the same, maybe even got a bit worse (hard to tell).

You're right though, I noticed even in Google Docs the scanner doesn't reduce the sensitivity of the touch, but it does appear much smoother than in this app. Same with Genius Scanner, it seems nice and smooth. There's something else going on with the touch that is making it not smooth.

Does anyone else see it, on another device aside from the Pixel 7 Pro (that I have)? 

I may be able to test this on another phone later on...

**Comment by farfromrefug** [comment]
@48-mq Understand you still have an issue. But i am not sure i understand exactly what the issue is. Could you make a video with debug tap location enabled? That way i will see how the magnifier moved compared to your touch.
BTW i now have a Pixel 6a for testing and i dont see something wrong there.

**Comment by 48-mq** [comment]
> @48-mq Understand you still have an issue. But i am not sure i understand exactly what the issue is. Could you make a video with debug tap location enabled? That way i will see how the magnifier moved compared to your touch. BTW i now have a Pixel 6a for testing and i dont see something wrong there.

This link will remain available for 89 more days: https://drop.siick.fr/1723740167-59/screen-20240517-122501.mp4

**Comment by farfromrefug** [comment]
@48-mq thanks for the video got it. The only thing i think i am seeing in the video is the magnifier seems to be "stuttering"  a bit. But could be due to the video. 
Whats your phone resolution? seems really high? Could be related to that
