### ISSUE TITLE
[BUG] iOS application does not work with WebDAV set up from the android app

### ISSUE THREAD

**Issue by DhruvaSambrani** [Akylas/OSS-DocumentScanner#204]
### Version

1.5.0

### What platform are you using?

iOS

### OS Version

Latest

### What happened?

Title.

Exact error: Unique constraint failed document.Id

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhruvaSambrani** [comment]
I think the error is because the FoxyDroid version is 1.8.0/72, but the IOS store version is older. Is it possible to update the IOS app? You may also want to use TestFlight incase the IOS store has some update rate limiting

**Comment by DhruvaSambrani** [comment]
Reinstalled and tried to set up the webdav.

This time, the **first** error is `table Page has no column named brightness`, and then when I try it again, it gives me the unique constraint failure.

The failed import on the first sync leaves the db in a bad state, it seems.

**Comment by farfromrefug** [comment]
@DhruvaSambrani  i see what s happening now. And you were right it could be due to the incompatible versions. The android version does support that new brightness column while the ios version does not.
Hopefully new iOS version coming real soon. Sorry about the trouble

Still an issue though that such an error `table Page has no column named brightness` should not put your db in a bad state. Will look at it

**Comment by DhruvaSambrani** [comment]
Also, it might be useful to add some checks so that backward compatibility is somewhat maintained.

**Comment by farfromrefug** [comment]
@DhruvaSambrani it is all implemented and new iOS version is waiting for review
