### ISSUE TITLE
Adding NFC Banking cards

### ISSUE THREAD

**Issue by cs-nero** [Akylas/OSS-DocumentScanner#247]
**Describe the solution you'd like**
Hey! Thanks for your great app!
Is it possible to add support for banking cards? They are working with NFC, arent they? I am absoluteley not an expert so please dont be mad at me😄

**Comment by farfromrefug** [comment]
@cs-nero thanks!
I actually wanted to have something like that.
Well what exactly are you looking for?
* only read and store NFC card in phone 
* read your NFC card and emulate it using your phone ?

The second would be awesome but will surely not be possible for security reason (otherwise someone could copy your card by putting a phone close to your card in the metro or something)

**Comment by cs-nero** [comment]
I was looking to pay with your app.
It is possible with Google/Apple/Samsung Wallet. 

Answer to the security thing:
The phone should only emulate the card if it is unlocked and the card is selected in the Wallet app

**Comment by farfromrefug** [comment]
OK no that is not possible  Samsung / google/... Have partnership with your bank to allow that.
I will never be able to do that :s

**Comment by cs-nero** [comment]
That is so sad! :(
Thanks for your reply!
