### ISSUE TITLE
[Suggestion]s Add gallery export and high quality scanning.

### ISSUE THREAD

**Issue by andrei-akopian** [Akylas/OSS-DocumentScanner#7]
Gallery export:
- I would like to export the scans I make as .png or .jpeg and save them to the file system individually.

High quality scanning:
- This is a very difficult demand and I know that. I would like to be able to make scans of higher quality (in terms of resolution/blur) than my phone's camera by combining multiple closeup pictures that fit only a part of the document (+ a normal scan if that helps with algorithm implementation). As far as I know no other document scanner app has a feature like that, so if it was implemented it would be a big win over CamScanner and MS Lens.

Thanks for the hard work on the app, keep up the good work!

**Comment by farfromrefug** [comment]
@andrei-akopian thanks for the kind words.
I will add a way to save to the gallery .will be on a per page basis, there is already a share button when you look at a document page. 
About the high quality scanning, i wont add it any time soon though. If you ever find a way to do that with opencv let me know and i can look at it

**Comment by JobLeonard** [comment]
I was also going to ask for png and/or jpg support, but since that's already here I'll share my current workaround: use the share button to share an image to a chat app (I use the "notes to self" thread in Signal myself, and post the shared image in high quality).

Also wish to note I'm really happy with the other features this app already supports - simple picture export is pretty much all I miss for my own use-case!

**Comment by JobLeonard** [comment]
(depending on how hard it is to find/integrate a good library to do the heavy lifting, [DjVu](https://en.wikipedia.org/wiki/DjVu) might also be a nice format to support since it compresses *much* better than PDF for scanned documents in my experience, even with OCR)

**Comment by farfromrefug** [comment]
@JobLeonard @andrei-akopian Right now you can long press the share icon (per page), it will export the image into the download folder.
Are you asking for a popover like the one for pdf export where:
* you can select the export folder
* share the image through the native share "view"
* export the image (as jpg) in the selected export folder


Would that be ok?

**Comment by andrei-akopian** [comment]
Yeah, I think that would be great.

**Comment by JobLeonard** [comment]
Yeah, that would work!

Just a mention: 1-bit black and white exports are likely a common use case, and then PNG is likely to compress *better* than JPEG while also avoiding the typical JPEG artifacts. So that might also be a nice feature to add in the future.

**Comment by farfromrefug** [comment]
@andrei-akopian this has been released. Let me know what you think

**Comment by andrei-akopian** [comment]
@farfromrefug Yes, thank you very much, I like it. Small but does everything you need it to.

Have a great day!

**Comment by senntore** [comment]
@farfromrefug would it be possible to batch export the scans to a jpg or png file?
In current implementation I have to open each scan manually & then share/export. It's very time consuming when I've many scans.

**Comment by farfromrefug** [comment]
@senntore yes i can do something to export all pages at once. But you wont have any saying over the naming. And it will be JPG. Is that good enough?

**Comment by senntore** [comment]
@farfromrefug Yes, that would be exactly what I need. Though it would be great if the naming convention is based on the order of the scan(something like the date/time).

**Comment by farfromrefug** [comment]
@senntore if i can yes pages images will have as a name the date of their creation. Should not 2 with the same date. If so i will add something like _2

**Comment by JobLeonard** [comment]
> Is that good enough?

Even if it isn't it's a start! There's always room for improvement later :)

**Comment by in-plaintext** [comment]
Lossless export (in PNG) would benefit a lot as the text readability is improved due to the lack of compression artifacts. It appears that many companies still exclusively use printed documents for employment contracts and recommendation letters. For instance government agencies may reject low-quality copies.

Please implement lossless scanning if by any means possible.

**Comment by farfromrefug** [comment]
@in-plaintext for now the app indeed only exports in JPEG. I will add PNG export. Is that ok if it is a global setting? (not on a per export basis)

**Comment by in-plaintext** [comment]
> @in-plaintext for now the app indeed only exports in JPEG. I will add PNG export. Is that ok if it is a global setting? (not on a per export basis)

Sure, a global setting is likely preferred by most (certainly by me!).

**Comment by farfromrefug** [comment]
@in-plaintext @andrei-akopian  it is now released as well as save in gallery

**Comment by user-1-2-3-4-5** [comment]
@farfromrefug The PNG images appear to be converted from JPG since there's always clear artifacting with text and graphics.

Is it viable to implement true lossless scanning? Would this necessitate capturing in the RAW format (for which phones appear to have limited support — I've used [Open Camera](https://sourceforge.net/p/opencamera/) for pictures)?

**Comment by farfromrefug** [comment]
@in-plaintext the androidx camera lib (used my most apps today) force jpeg compression because of computing time and memory (last time i checked).

The only thing youncan try to improvis to put jpeg quality to 100% in image expoet settings
Let me know if it helps

**Comment by user-1-2-3-4-5** [comment]
> [@in-plaintext](https://github.com/in-plaintext) the androidx camera lib (used my most apps today) force jpeg compression because of computing time and memory (last time i checked).
> 
> The only thing you can try to improve is to put jpeg quality to 100% in image export

[I fixed some typos]

Thank you, the JPG compression level was  at 80%.

You may want to default to `100` for PNG since this likely is what most people who've changed the setting want. 
Also please clarify in the options menu that  PNG  originates from a lossy [JPG?] format (how the aforementioned Open Camera operates).
