### ISSUE TITLE
Magnifying glass in corner

### ISSUE THREAD

**Issue by justTOBBI** [Akylas/OSS-DocumentScanner#81]
Hey, nice work on the app so far. 
One thing I noticed when scanning my first document was, that when adjusting the frame around the document, the magnified Section is not visible, due to the finger beeing above it.

Expected behavior: have a corner with the magnified section so that one can adjust the frame better :)

**Comment by farfromrefug** [comment]
@justTOBBI Thanks!
You are not the first one to have that issue. It is not the first thing you see but you dont need to press "on" the corner to select it. I will select the closest one. Consequently you can touch a bit on the side so that you always see the magnifying glass.
I might add a text explanation on that view.
